/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mx.com.boletera.form;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import mx.com.boletera.bo.ConfigurarReglaBO;
import mx.com.boletera.model.Regla;

/**
 *
 * @author jcano
 */
public class FormConfigurarRegla extends JDialog {

    /**
     * Creates new form FormConfigurarExcluyente
     */
    public FormConfigurarRegla() {
        initComponents();
        configurarReglaBO = new ConfigurarReglaBO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegla = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDigito = new javax.swing.JLabel();
        lblPosicion = new javax.swing.JLabel();
        txtDigito = new javax.swing.JTextField();
        txtPosicion = new javax.swing.JTextField();
        wrnDigito = new javax.swing.JLabel();
        wrnPosicion = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        pnlRegla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRegla.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblTitulo.setText("Configurar regla excluyente");
        pnlRegla.add(lblTitulo);
        lblTitulo.setBounds(8, 8, 188, 21);

        lblDigito.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblDigito.setText("Dígito");
        pnlRegla.add(lblDigito);
        lblDigito.setBounds(10, 50, 109, 21);

        lblPosicion.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblPosicion.setText("Posición");
        pnlRegla.add(lblPosicion);
        lblPosicion.setBounds(10, 100, 109, 21);

        txtDigito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDigito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDigitoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDigitoFocusLost(evt);
            }
        });
        pnlRegla.add(txtDigito);
        txtDigito.setBounds(90, 50, 120, 28);

        txtPosicion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPosicion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPosicionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPosicionFocusLost(evt);
            }
        });
        pnlRegla.add(txtPosicion);
        txtPosicion.setBounds(90, 100, 120, 28);

        wrnDigito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/warning.png"))); // NOI18N
        wrnDigito.setToolTipText("Datos no válidos");
        wrnDigito.setFocusable(false);
        wrnDigito.setVisible(false);
        pnlRegla.add(wrnDigito);
        wrnDigito.setBounds(220, 50, 16, 20);

        wrnPosicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/warning.png"))); // NOI18N
        wrnPosicion.setToolTipText("Datos no válidos");
        wrnPosicion.setFocusable(false);
        wrnPosicion.setVisible(false);
        pnlRegla.add(wrnPosicion);
        wrnPosicion.setBounds(220, 100, 16, 20);

        getContentPane().add(pnlRegla);
        pnlRegla.setBounds(10, 10, 250, 160);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accept.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(280, 20, 140, 44);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(280, 70, 140, 47);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/repeat.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(280, 120, 140, 47);

        setBounds(0, 0, 445, 214);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Boolean valido = true;
        //folio inicial
        Integer digito = 0;
        String valor = txtDigito.getText();
        boolean cumplePatron = Pattern.matches("^[0-9]{1}$", valor);
        if (cumplePatron) {
            try {
                digito = Integer.parseInt(txtDigito.getText().trim());
            } catch (Exception e) {
                wrnDigito.setVisible(true);
                txtDigito.setBackground(Color.red);
                valido = false;
            }
        } else {
            wrnDigito.setVisible(true);
            txtDigito.setBackground(Color.red);
            valido = false;
        }

        //folio final
        Integer posicion = 0;
        valor = txtPosicion.getText();
        cumplePatron = Pattern.matches("^[0-9]{1}$", valor);
        if (cumplePatron) {
            try {
                posicion = Integer.parseInt(txtPosicion.getText().trim());
            } catch (Exception e) {
                wrnPosicion.setVisible(true);
                txtPosicion.setBackground(Color.red);
                valido = false;
            }
        } else {
            wrnPosicion.setVisible(true);
            txtPosicion.setBackground(Color.red);
            valido = false;
        }

        if (valido) {
            try {
                Regla regla = new Regla();
                regla.setDigito(digito);
                regla.setPosicion(posicion);
                regla = configurarReglaBO.insertarRegla(regla);
                JOptionPane.showMessageDialog(this, "Regla insertada con exito");
                this.setVisible(false);
            } catch (Exception ex) {
                Logger.getLogger(FormConfigurarRegla.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Revise los datos ingresados");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Integer res = JOptionPane.showConfirmDialog(this, "¿Desea cancelar la operacion?", "Salir", JOptionPane.YES_NO_OPTION);
        if (res.equals(0)) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDigitoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDigitoFocusGained
        wrnDigito.setVisible(false);
        txtDigito.setBackground(Color.white);
    }//GEN-LAST:event_txtDigitoFocusGained

    private void txtDigitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDigitoFocusLost
        String valor = txtDigito.getText();
        boolean cumplePatron = Pattern.matches("^[0-9]{1,7}$", valor);
        if (!cumplePatron) {
            wrnDigito.setVisible(true);
            txtDigito.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtDigitoFocusLost

    private void txtPosicionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPosicionFocusGained
        wrnPosicion.setVisible(false);
        txtPosicion.setBackground(Color.white);
    }//GEN-LAST:event_txtPosicionFocusGained

    private void txtPosicionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPosicionFocusLost
        String valor = txtPosicion.getText();
        boolean cumplePatron = Pattern.matches("^[0-9]{1,7}$", valor);
        if (!cumplePatron) {
            wrnPosicion.setVisible(true);
            txtPosicion.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtPosicionFocusLost

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtDigito.setText("");
        txtDigito.setBackground(Color.white);
        wrnDigito.setVisible(false);
        txtPosicion.setText("");
        txtPosicion.setBackground(Color.white);
        wrnPosicion.setVisible(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel lblDigito;
    private javax.swing.JLabel lblPosicion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlRegla;
    private javax.swing.JTextField txtDigito;
    private javax.swing.JTextField txtPosicion;
    private javax.swing.JLabel wrnDigito;
    private javax.swing.JLabel wrnPosicion;
    // End of variables declaration//GEN-END:variables
    private ConfigurarReglaBO configurarReglaBO;
}
