/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mx.com.boletera.form;

import java.awt.event.MouseEvent;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import mx.com.boletera.bo.ConfigurarBoletoBO;
import mx.com.boletera.util.PanelBoleto;

/**
 *
 * @author jkano
 */
public class FormConfigurarBoleto extends JDialog {

    /**
     * Creates new form Test
     */
    public FormConfigurarBoleto() {
        initComponents();
        configurarBoletoBO = new ConfigurarBoletoBO();
        pnlHoja = new PanelBoleto("pnlBoleto");
        pnlHoja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlHoja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        pnlHoja.setBounds(10,10, 380, 380);
        pnlBoleto.add(pnlHoja);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBoleto = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        getContentPane().setLayout(null);

        pnlBoleto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBoleto.setLayout(null);
        getContentPane().add(pnlBoleto);
        pnlBoleto.setBounds(10, 10, 380, 400);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accept.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(440, 170, 150, 44);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(440, 240, 150, 44);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/repeat.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(440, 310, 150, 44);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(430, 10, 140, 140);

        setBounds(0, 0, 628, 477);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Integer res = JOptionPane.showConfirmDialog(this, "¿Desea cancelar la operacion?", "Salir", JOptionPane.YES_NO_OPTION);
        if (res.equals(0)) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        pnlHoja.clearPosicion();
        repaint();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBoleto;
    // End of variables declaration//GEN-END:variables
    private PanelBoleto pnlHoja;
    private ConfigurarBoletoBO configurarBoletoBO;
    
    private void jPanel1MouseClicked(MouseEvent evt) {
        JOptionPane.showMessageDialog(this, evt.getX());
        JOptionPane.showMessageDialog(this, evt.getY());
        pnlHoja.addPosicion(evt.getX(), evt.getY(), 100, 100, 100, 20);
        repaint();
    }
}
